### ISSUE TITLE
Ceres startet from a Power Automate Desktop flow

### ISSUE THREAD

**Issue by sandersfrank** [dje-dev/Ceres#72]
If I start Ceres (v0.96) in a command line session with PAD I get the following error:

Loaded network weights: 0 10x128 WDL MLH  from ./Networks/weights_run2_703810.pb.gz

   at Ceres.Chess.NNBackends.CUDA.NNBackendLC0_CUDA..ctor(Int32 gpuID, Net net, Boolean saveActivations, Int32 maxBatchSize, Boolean dumpTiming, Boolean enableCUDAGraphs, Int32 graphBatchSizeDivisor, NNBackendLC0_CUDA referenceBackend) in C:\dev\Ceres\src\Ceres.Chess\NNBackends\CUDA\NNBackendLC0_CUDA.cs:line 270
Error when initializing CUDA. Did you install NVidia's CUDA? https://developer.nvidia.com/cuda-zone
System.DllNotFoundException: Unable to load DLL 'cublas64_11' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at ManagedCuda.CudaBlas.CudaBlasNativeMethods.cublasCreate_v2(CudaBlasHandle& handle)
   at ManagedCuda.CudaBlas.CudaBlas..ctor()
   at Ceres.Chess.NNBackends.CUDA.NNBackendLC0_CUDA.InitCUDAContextAndTakeWriteLock() in C:\dev\Ceres\src\Ceres.Chess\NNBackends\CUDA\NNBackendLC0_CUDA.cs:line 324
   at Ceres.Chess.NNBackends.CUDA.NNBackendLC0_CUDA..ctor(Int32 gpuID, Net net, Boolean saveActivations, Int32 maxBatchSize, Boolean dumpTiming, Boolean enableCUDAGraphs, Int32 graphBatchSizeDivisor, NNBackendLC0_CUDA referenceBackend) in C:\dev\Ceres\src\Ceres.Chess\NNBackends\CUDA\NNBackendLC0_CUDA.cs:line 270
   at ManagedCuda.CudaBlas.CudaBlasNativeMethods.cublasCreate_v2(CudaBlasHandle& handle)
   at ManagedCuda.CudaBlas.CudaBlas..ctor()
   at Ceres.Chess.NNBackends.CUDA.NNBackendLC0_CUDA.InitCUDAContextAndTakeWriteLock() in C:\dev\Ceres\src\Ceres.Chess\NNBackends\CUDA\NNBackendLC0_CUDA.cs:line 324
   at Ceres.Chess.NNBackends.CUDA.NNBackendLC0_CUDA..ctor(Int32 gpuID, Net net, Boolean saveActivations, Int32 maxBatchSize, Boolean dumpTiming, Boolean enableCUDAGraphs, Int32 graphBatchSizeDivisor, NNBackendLC0_CUDA referenceBackend) in C:\dev\Ceres\src\Ceres.Chess\NNBackends\CUDA\NNBackendLC0_CUDA.cs:line 270

CUDA driver is installed, and starting by hand in a command line window works without problems.

**Comment by dje-dev** [comment]
The error message stats that the cublas64_11.dll file cannot be found. I do not understand the specifics of how PAD works, but I suggest you locate this file and put it somewhere on the system path so it can be found by a program running from any directory. This will hopefully solve the issue.
